version: '3.9'

services:

  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: ["start-dev", "--import-realm"]
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      ROOT_LOGLEVEL: DEBUG
      JBOSS_LOG_MANAGER_ROOT_LOGGER: DEBUG, stdout, FILE

    ports:
      - "8065:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import

    depends_on:
      - postgres-keycloak

    networks:
      - spring


  postgres-keycloak:
    image: postgres
    ports:
      - "5436:5432"  # First is external and second is internal
    container_name: postgres-keycloak
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/keycloak:/var/lib/postgresql/data
    networks:
      - spring

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8887:80"  # First is external and second is internal
    container_name: pgadmin-keycloak
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password

    depends_on:
      - postgres-keycloak

    networks:
      - spring

networks:
  spring:
    driver: bridge